services:
    graphcast:
        container_name: graphcast
        image: graphcast
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        volumes: 
            - C:\Users\path:/app